### ISSUE TITLE
Node v18.0.0

### ISSUE THREAD

**Issue by donavanbecker** [homebridge/ciao#24]
### Analysis

Not able to run with Node v18.0.0

### Expected Behavior

load successful

### Steps To Reproduce

Install Node 18.0.0 and then restart homebridge

### Logs

```markdown
AssertionError [ERR_ASSERTION]: Could not find valid addresses for interface 'anpi2'
    at NetworkManager.getCurrentNetworkInterfaces (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/NetworkManager.ts:419:13)
    at /usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/NetworkManager.ts:166:12
    at new Promise (<anonymous>)
    at new NetworkManager (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/NetworkManager.ts:165:24)
    at new MDNSServer (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:193:27)
    at new Responder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:129:19)
    at Function.getResponder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:121:25)
    at Object.getResponder (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/index.ts:52:20)
    at new CiaoAdvertiser (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Advertiser.ts:112:27)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1232:26)
```

### Configuration

```json
N/A
```

### Environment

- OS: macOS 12.4 beta 2
- Software: Homebridge 1.4.0
- Node: 18.0.0
- npm: 8.6.0

### Process Supervisor

hb-service

### Additional Context

Not a huge issue currently since it is easy to move back with hb-service, but figured I would post this to make people aware.

[Homebridge Issue](https://github.com/homebridge/homebridge/issues/3114)

**Comment by oznu** [comment]
Fixed in 1.1.4, thank you for reporting!
