### ISSUE TITLE
ERROR while installation process

### ISSUE THREAD

**Issue by vVJoKeRVv** [homebridge/ciao#29]
### Current Situation

Hello
i tried to install pyatv and got the following problem (see log). I have already asked the team (https://github.com/postlund/pyatv/issues/1907#event-8381438238)of pyatv for a solution but they say that it is a problem of zeroconf.
could you help me please?
thanks

### Logs

```markdown
Collecting zeroconf>=0.38.1
Using cached zeroconf-0.47.1.tar.gz (60 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
status = run_func(*args)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
return func(self, options, args)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
requirement_set = resolver.resolve(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
result = self._result = resolver.resolve(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
failure_causes = self._attempt_to_pin_criterion(name)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
criteria = self._get_updated_criteria(candidate)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
self._add_to_criteria(criteria, requirement, parent=candidate)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
if not criterion.candidates:
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in bool
return bool(self._sequence)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in bool
return any(self)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in
return (c for c in iterator if id(c) not in self._incompatible_ids)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
candidate = func()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in init
super().init(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in init
self.dist = self._prepare()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
dist = self._prepare_distribution()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
dist = _get_prepared_distribution(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
abstract_dist.prepare_distribution_metadata(
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
self._install_build_reqs(finder)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
build_reqs = self._get_build_requires_wheel()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
return backend.get_requires_for_build_wheel()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
return super().get_requires_for_build_wheel(config_settings=cs)
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 173, in get_requires_for_build_wheel
return self._call_hook('get_requires_for_build_wheel', {
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
obj = import_module(mod_path)
File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 992, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 992, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 992, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'
```

### Configuration

```json
"bridge": {
        "port": 51421,
        "username": "0E:E9:52:3C:FC:94",
        "name": "Homebridge Mini",
        "pin": "329-01-057",
        "advertiser": "ciao",
        "bind": [
            "en0"
        ]
    },
    "disabledPlugins": [
        "@milo526/homebridge-tuya-web"
    ],
    "platforms": [
        {
            "lang": "de",
            "theme": "cyan",
            "name": "HomeBridgemac",
            "platform": "config",
            "port": 8581,
            "tempUnits": "c",
            "auth": "none"
        },
        {
            "country": "LU",
            "devices": [
                {
                    "ac_fan_control": true,
                    "name": "Klimatisation",
                    "ac_mode": "BOTH",
                    "id": "2268f3eb-5d94-1a49-aefc-xxxxxxxxx",
                    "ac_swing_mode": "BOTH",
                    "type": "AC",
                    "ac_temperature_sensor": true
                }
            ],
            "username": "",
            "thinq1": true,
            "refresh_token": "xxxxxxxxx",
            "platform": "LGThinQ",
            "_bridge": {
                "username": "xxxxxxxx",
                "port": 51921
            },
            "refresh_interval": 60,
            "password": "",
            "language": "de-LU",
            "auth_mode": "token"
        },
        {
            "scenes": false,
            "_bridge": {
                "username": "0xxxxxxxx6",
                "port": 40749
            },
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxxx",
                "countryCode": "352",
                "platform": "smart_life",
                "password": "xxxxxxxx"
            },
            "defaults": [
                {
                    "device_type": "dimmer",
                    "id": "bf18029b2xxxxxxxx",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "device_type": "dimmer",
                    "id": "bf67978eaa51xxxxxxx",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "platform": "TuyaWebPlatform"
        },
        {
            "_bridge": {
                "port": 58872,
                "username": "0E:74:AE:15:2D:48"
            },
            "platform": "TuyaPlatform",
            "options": {
                "accessKey": "xxxxxxxxx",
                "endpoint": "xxxxxxxxxxxx/",
                "deviceOverrides": [
                    {
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    }
                ],
                "countryCode": 352,
                "accessId": "xxxxxxxxt",
                "projectType": "2",
                "appSchema": "smartlife",
                "username": "xxxxxxxxxxxx",
                "password": "xxxxxxxxxx"
            }
        },
        {
            "whiteEffects": {
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5,
                "simultaniousDevicesColorWhite": true
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist",
                "blacklistedUniqueIDs": [
                    ""
                ]
            },
            "platform": "homebridge-magichome-dynamic-platform",
            "pruning": {
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false,
                "pruneMissingCachedAccessories": false
            },
            "advancedOptions": {
                "logLevel": 3,
                "periodicDiscovery": true,
                "namesWithMacAddress": false
            },
            "_bridge": {
                "username": "0E:BF:C9:A4:B2:C1",
                "port": 48625
            }
        },
        {
            "devices": [
                {
                    "auth": false,
                    "enableDebugMode": false,
                    "infoButtonCommand": "138",
                    "sensorVolume": false,
                    "sensorPower": false,
                    "mqttAuth": false,
                    "disableLogDeviceInfo": false,
                    "port": 80,
                    "enableMqtt": false,
                    "host": "192.168.178.43",
                    "disableLogInfo": false,
                    "mqttDebug": false,
                    "sensorMute": false,
                    "name": "VU+",
                    "volumeControl": 1
                }
            ],
            "platform": "OpenWebIfTv",
            "_bridge": {
                "port": 45341,
                "username": "0E:9A:63:29:28:8D"
            }
        },
        {
            "homepodId": "58:D3:49:xxxxxxxx",
            "serialNumber": "xxxxxxxxxx",
            "httpPort": 7654,
            "verboseModel": false,
            "volumeControl": true,
            "radios": [
                {
                    "name": "Eldoradio",
                    "radioUrl": "https://stream.rtl.lu/live/hls/radio/eldo",
                    "volume": 20,
                    "autoResume": false
                },
                {
                    "name": "Laurent",
                    "radioUrl": "https://youtu.be/6Q7tdD5lJxg",
                    "volume": 61
                },
                {
                    "name": "BBC - Radio 1",
                    "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one"
                }
            ],
            "_bridge": {
                "username": "0E:C2:BD:1E:42:BB",
                "port": 30155
            },
            "platform": "HomepodRadioPlatform"
        }
    ],
    "accessories": [
        {
            "accessory": "DummyGarage",
            "_bridge": {
                "username": "A6:DE:8D:6E:6C:89",
                "port": 58818
            },
            "autoCloseDelay": 10,
            "name": "Sesam"
        }
    ]
}
```

### Environment

My system:
-Mac Ventura 13.2
-Homebridge 2.0 beta
-Node : v16.16.0
-npm: 9.4.0
-Homebrew installed (latest version)
-ffmpeg installed (latest version)
-python installed (latest version)

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This is CIAO and not zeroconf, pls open against the correct REPO

**Comment by Supereg** [comment]
Seemingly pyatv is a requirement of the [homebridge-homepod-radio](https://www.npmjs.com/package/@petro-kushchak/homebridge-homepod-radio) plugin.
So might be worth it raising an issue over there.
