### ISSUE TITLE
Reached illegal state! IPV4 address change from defined to undefined

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/ciao#50]
### Current Situation

Since updating code based to HAP-Nodejs 1.10 and subsequently having ciao updated to 1.3.0, been seeing these errors below in my accessory logs

Thoughts on why now occurring?

```
AssertionError [ERR_ASSERTION]: Reached illegal state! IPV4 address change from defined to undefined!
    at MDNSServer.handleUpdatedNetworkInterfaces (/opt/Nest_accfactory/node_modules/@homebridge/ciao/src/MDNSServer.ts:695:18)
    at NetworkManager.emit (node:events:531:35)
    at NetworkManager.checkForNewInterfaces (/opt/Nest_accfactory/node_modules/@homebridge/ciao/src/NetworkManager.ts:345:12)
```

### Logs

```markdown
AssertionError [ERR_ASSERTION]: Reached illegal state! IPV4 address change from defined to undefined!
    at MDNSServer.handleUpdatedNetworkInterfaces (/opt/Nest_accfactory/node_modules/@homebridge/ciao/src/MDNSServer.ts:695:18)
    at NetworkManager.emit (node:events:531:35)
    at NetworkManager.checkForNewInterfaces (/opt/Nest_accfactory/node_modules/@homebridge/ciao/src/NetworkManager.ts:345:12)
```

### Configuration

```json
.
```

### Environment

- OS: Docker NodeJS image, 20-Alpine3.20
- Software:
- Node: 20.15.1
- npm: 108.2

### Process Supervisor

other (Explain in `Additional Context`)

**Comment by n0rt0nthec4t** [comment]
This is not stale.. Still occuring

Aug 28 09:36:00 garagedoor node[11165]: AssertionError [ERR_ASSERTION]: Reached illegal state! IPV4 address change from defined to undefined!
Aug 28 09:36:00 garagedoor node[11165]:     at MDNSServer.handleUpdatedNetworkInterfaces (/home/pi/node_modules/@homebridge/ciao/src/MDNSServer.ts:695:18)
Aug 28 09:36:00 garagedoor node[11165]:     at NetworkManager.emit (node:events:526:35)
Aug 28 09:36:00 garagedoor node[11165]:     at NetworkManager.checkForNewInterfaces (/home/pi/node_modules/@homebridge/ciao/src/NetworkManager.ts:345:12)
Aug 28 09:36:00 garagedoor node[11165]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by hjdhjd** [comment]
If you can recreate this, at will, turn on debugging please. There should be network change messages around it like `Detected network changes` that will provide a bit more context. I’ve struggled to recreate this one at will, unfortunately, and without that…I need data. 😄 

Add the environment variable:

```
DEBUG=ciao:NetworkManager
```

And let’s see what comes up in/around the assertion error that’s generated and let’s get this one tracked down for everyone’s sake. 😄

**Comment by n0rt0nthec4t** [comment]
@hjdhjd 

Oct 27 17:34:28 irrigation node[19804]: 2024-10-27T06:34:28.182Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , fd13:730d:c0d0:c945:509b:4bd2:3713:6503 -> undefined }]!
Oct 27 17:35:43 irrigation node[19804]: 2024-10-27T06:35:43.577Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , undefined -> fd13:730d:c0d0:c945:509b:4bd2:3713:6503 }]!

**Comment by n0rt0nthec4t** [comment]
@hjdhjd 

Oct 28 18:17:21 irrigation node[19804]: 2024-10-28T07:17:21.037Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , fd13:730d:c0d0:c945:509b:4bd2:3713:6503 -> undefined }]!
Oct 28 18:18:36 irrigation node[19804]: 2024-10-28T07:18:36.421Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , undefined -> fd13:730d:c0d0:c945:509b:4bd2:3713:6503 }]!
Oct 29 10:02:04 irrigation node[19804]: 2024-10-28T23:02:04.385Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , fd13:730d:c0d0:c945:509b:4bd2:3713:6503 -> undefined }]!
Oct 29 10:04:50 irrigation node[19804]: 2024-10-28T23:04:50.176Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , undefined -> fd13:730d:c0d0:c945:509b:4bd2:3713:6503 }]!
Oct 29 10:49:33 irrigation node[19804]: 2024-10-28T23:49:33.131Z ciao:NetworkManager Detected network changes: added: [], removed: [], changes: [{ name: wlan0 , 10.0.1.136 -> undefined , fd13:730d:c0d0:c945:509b:4bd2:3713:6503 -> undefined }]!
Oct 29 10:49:33 irrigation node[19804]: AssertionError [ERR_ASSERTION]: Reached illegal state! IPV4 address change from defined to undefined!
Oct 29 10:49:33 irrigation node[19804]:     at MDNSServer.handleUpdatedNetworkInterfaces (/home/pi/node_modules/@homebridge/ciao/src/MDNSServer.ts:695:18)
Oct 29 10:49:33 irrigation node[19804]:     at NetworkManager.emit (node:events:526:35)
Oct 29 10:49:33 irrigation node[19804]:     at NetworkManager.checkForNewInterfaces (/home/pi/node_modules/@homebridge/ciao/src/NetworkManager.ts:345:12)
Oct 29 10:49:33 irrigation node[19804]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by hjdhjd** [comment]
Thanks, @n0rt0nthec4t I'll take a closer look this week. Offhand it looks like the WiFi interface is losing it's connectivity, and therefore it's IPs...and then reacquiring them a few moments to minutes later.

Appreciate your help capturing the data to this point. Will update with more as I track this down further.

**Comment by n0rt0nthec4t** [comment]
Some other observations, this only starting occurring in like a recent version of CIAO. maybe 1.2 or later? Doesnt seem to happen with bonjour or AVAHI, but thats just conjecture

**Comment by hjdhjd** [comment]
I’m aware - don’t need more data at this time. Will get back to you when more info or testing is needed. Thanks. 😄

**Comment by mishakim** [comment]
I'm having the same error on a new Raspberry Pi 5, standard Homebridge image with a setup restored from a long-term install on a Mac Mini that finally failed.  It intermittently loses connectivity, and seems to also restart Homebridge on its own at least some of the times that the network resets. 

Reviewing the logs after the most recent night of frequent restarts, one of the restarts was preceded by the same error as in the original report, which came after repeated lines of:
`Warning: no IPv4 address available on eth0`

I get those no IPv4 address errors a lot - not always accompanied by restarts.
I think the network loss is unrelated to Homebridge - I also lose ssh and pi-hole, then everything comes back a bit later. But home bridge doesn't seem to like it. So I'm trying to fix that problem, but thought I should chime in on this thread to report that it's not limited to n0rt0nthec4t's config.

Environment
OS: Debian Bookworm (12)
Node: 20.18.0
npm: 10.8.2
Raspberry Pi 5, 4GB, no accessories except the fan connected, also running pi-hole and wireguard, nothing else

**Comment by hjdhjd** [comment]
While I appreciate the earnestness, **I don’t need any additional feedback at this time on this issue.** It’ll be resolved in an upcoming update. Thanks!

I should also add: please keep Homebridge reports in the Homebridge issue log, and **ciao** reports here. Ciao is an underlying capability and ciao is not Homebridge, and Homebridge is not ciao. 😄 Ciao is a network support library, not an end user product. We keep things separated so we can focus appropriately. Thanks!

@mishakim I should also add: nobody using Linux should be using ciao for Homebridge. Read the Homebridge wiki or other sources for details…but again, none of that belongs here. 😄 Thanks!

**Comment by n0rt0nthec4t** [comment]
Why is this closed? It still an issue waiting to be addressed
